name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macOS-swift-latest:
    name: macOS (Swift Latest)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -v -c debug
    - name: Build (Release)
      run: swift build -v -c release
   # - name: Test (Debug)
   #   run: swift test -v --configuration debug --enable-test-discovery
   # - name: Test (Release)
   #   run: swift test -v --configuration release -Xswiftc -enable-testing
    
  linux-swift-53:
    name: Linux x86_64 (Swift 5.3)
    runs-on: ubuntu-20.04
    container: swift:5.3-focal
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -v -c debug --enable-test-discovery
    - name: Build (Release)
      run: swift build -v -c release --enable-test-discovery
    #- name: Test (Debug)
    #  run: swift test -v --configuration debug --enable-test-discovery
    #- name: Test (Release)
    #  run: swift test -v --configuration release -Xswiftc -enable-testing --enable-test-discovery
    
  windows-swift-latest:
    name: Windows (Development Snapshot)
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
         - tag: 5.5.2-RELEASE
           branch: swift-5.5.2-release
         - tag: DEVELOPMENT-SNAPSHOT-2021-12-23-a
           branch: development
           
    steps:
    - uses: compnerd/gha-setup-swift@main
      with:
        branch: ${{ matrix.branch }}
        tag: ${{ matrix.tag }}
    - uses: actions/checkout@v2
    
    - name: Swift Version
      run: swift --version
      
    - name: Build (Debug)
      run: swift build -c debug
      
    - name: Build (Release)
      run: swift build -c release
      
    #- name: Test (Debug)
    #  run: swift test --configuration debug --parallel
      
    #- name: Test (Release)
    #  run: swift test --configuration release -Xswiftc -enable-testing --parallel
